name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ajuste para sua branch principal

permissions:
  contents: write  # Permissão para gravar no repositório

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Prepare files
        run: |
          mkdir -p dist
          mkdir -p dist/css
          mkdir -p dist/js
          mkdir -p dist/images
          cp index.html dist/
          cp css/index.css dist/css/
          cp -r images/* dist/images/

      - name: Build
        env:
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages  # Explicitamente especifica a branch
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token para autenticação
          clean: true  # Remove arquivos antigos