name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Prepare files
        run: |
          mkdir -p dist
          mkdir -p dist/css
          mkdir -p dist/js
          mkdir -p dist/img
          cp index.html dist/
          cp css/index.css dist/css/
          cp -r img/* dist/img/

      - name: Build
        env:
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Adiciona o token padrão do GitHub