name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      # Copia arquivos estáticos e prepara a pasta dist/
      - name: Prepare files
        run: |
          mkdir -p dist
          mkdir -p dist/css
          mkdir -p dist/img
          mkdir -p dist/js  
          cp index.html dist/
          cp css/index.css dist/css/
          cp img/* dist/img/

      # Executa o build para processar o js/index.js
      - name: Build
        env:
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
        run: npm install && npm run build

      # Deploy para GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # Pasta com os arquivos finais